site_name: mkdocs-apidoc
nav:
    - Home: index.md
    - render: render.md
    - models: models.md
    - config: config.md

markdown_extensions:
  - def_list:
  - toc:
      permalink: true
  - pymdownx.highlight:
  - pymdownx.superfences:

theme:
  name: material
extra_css:
  - stylesheets/extra.css

plugins:
  - mkdocs_apidoc:
      log_level: WARN
      execute_and_insert_examples: true
